version: '3.8'

# Actual Budget
# Purpose: Personal finance and budget management
# Documentation: https://actualbudget.org/

services:
  actual-budget:
    image: actualbudget/actual-server:latest  # Using latest for better stability
    container_name: actual-budget
    restart: unless-stopped
    
    # Security
    security_opt:
      - no-new-privileges:true
    read_only: false  # Needs write access to /data
    
    # Network configuration
    networks:
      - traefik-network
    
    ports:
      - "5006:5006"
    
    # Volume mounts
    volumes:
      # Data directory (contains budgets and database)
      - actual-budget-data:/data
    
    # Environment variables
    environment:
      - TZ=America/New_York
      # Upload limits (optional)
      - ACTUAL_UPLOAD_FILE_SYNC_SIZE_LIMIT_MB=20
      - ACTUAL_UPLOAD_SYNC_ENCRYPTED_FILE_SYNC_SIZE_LIMIT_MB=50
      # Trust proxy headers from Caddy/Cloudflare (Podman network CIDR)
      - ACTUAL_TRUSTED_PROXIES=172.20.0.0/16
    
    # Health check - disabled due to false negatives
    # healthcheck:
    #   test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:5006"]
    #   interval: 60s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 30s
    
    labels:
      # Service identification
      - "com.miraclemax.service=actual-budget"
      - "com.miraclemax.version=24.10.1"
      - "com.miraclemax.description=Personal finance management"
      - "com.miraclemax.persona=ramit"  # Ramit persona context
      
      # Backup configuration (CRITICAL - financial data)
      - "com.miraclemax.backup=critical"
      - "com.miraclemax.backup.path=/data"
      - "com.miraclemax.backup.frequency=daily"
      - "com.miraclemax.backup.encryption=required"
      
      # Monitoring
      - "com.miraclemax.monitor=true"
      - "com.miraclemax.health.port=5006"
      
      # Traefik routing
      - "traefik.enable=true"
      - "traefik.http.routers.actual.rule=Host(`budget.miraclemax.local`)"
      - "traefik.http.services.actual.loadbalancer.server.port=5006"
      
      # Security: Recommend adding auth middleware
      # - "traefik.http.routers.actual.middlewares=auth@file"

# Named volumes
volumes:
  actual-budget-data:
    driver: local

# Networks
networks:
  traefik-network:
    external: true

