version: '3.8'

# Blackbox Exporter - External Endpoint Monitoring
# Purpose: Probe HTTP/HTTPS/TCP/ICMP endpoints, measure uptime and response times
# Enterprise Use: External monitoring, SSL cert expiry, endpoint availability

services:
  blackbox-exporter:
    image: prom/blackbox-exporter:v0.24.0
    container_name: blackbox-exporter
    restart: unless-stopped
    
    security_opt:
      - no-new-privileges:true
    
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
        reservations:
          cpus: '0.1'
          memory: 32M
    
    networks:
      - traefik-network
    
    ports:
      - "9115:9115"
    
    volumes:
      - ../config/blackbox/config.yml:/etc/blackbox_exporter/config.yml:ro
    
    command:
      - '--config.file=/etc/blackbox_exporter/config.yml'
      - '--log.level=info'
    
    environment:
      - TZ=America/New_York
    
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:9115/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    
    labels:
      - "com.miraclemax.service=blackbox-exporter"
      - "com.miraclemax.version=0.24.0"
      - "com.miraclemax.description=HTTP/HTTPS endpoint monitoring"
      - "com.miraclemax.monitor=true"
      - "prometheus.scrape=true"
      - "prometheus.port=9115"

networks:
  traefik-network:
    external: true

