version: '3.8'

# cAdvisor (Container Advisor)
# Purpose: Container resource usage and performance monitoring
# Documentation: https://github.com/google/cadvisor

services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.0  # Pinned version
    container_name: cadvisor
    restart: unless-stopped
    
    # Privileged mode required for full container metrics
    privileged: true
    
    # Resource limits (monitor the monitor)
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M
    
    # Network configuration
    ports:
      - "8084:8080"
    
    # Volume mounts (read-only access to system resources)
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/containers/:/var/lib/containers:ro
      - /dev/disk/:/dev/disk:ro
      
      # For Podman (instead of Docker)
      - /run/podman/podman.sock:/var/run/docker.sock:ro
    
    # Devices
    devices:
      - /dev/kmsg:/dev/kmsg
    
    # Command arguments
    command:
      # Storage driver
      - --docker=unix:///var/run/docker.sock
      
      # Housekeeping interval (reduce CPU usage)
      - --housekeeping_interval=30s
      
      # Disable metrics we don't need
      - --disable_metrics=percpu,sched,tcp,udp,disk,diskIO,hugetlb,referenced_memory,cpu_topology,resctrl
      
      # Store only recent data (reduce memory)
      - --max_housekeeping_interval=60s
      - --event_storage_event_limit=default=0
      - --event_storage_age_limit=default=0
      
      # Prometheus metrics
      - --enable_metrics=app,cpu,memory,network
    
    # Health check
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/healthz"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s
    
    labels:
      # Service identification
      - "com.miraclemax.service=cadvisor"
      - "com.miraclemax.version=0.47.0"
      - "com.miraclemax.description=Container metrics exporter"
      
      # Monitoring (it's the monitoring service)
      - "com.miraclemax.monitor=true"
      - "com.miraclemax.metrics.port=8080"
      - "com.miraclemax.metrics.path=/metrics"
      
      # Prometheus scraping
      - "prometheus.io/scrape=true"
      - "prometheus.io/port=8080"
      - "prometheus.io/path=/metrics"
      
      # Traefik routing (optional - usually internal only)
      # - "traefik.enable=true"
      # - "traefik.http.routers.cadvisor.rule=Host(`cadvisor.miraclemax.local`)"
      # - "traefik.http.services.cadvisor.loadbalancer.server.port=8080"
      # - "traefik.http.routers.cadvisor.middlewares=internal-only@file"

# Note: No volumes needed - all data is ephemeral metrics

