version: '3.8'

# GitLab Webhook Receiver for RFE & Bug Tracker
# Purpose: Receive GitLab issue notifications and send email alerts
# Documentation: /home/jbyrd/pai/docs/GITLAB-WEBHOOK-SETUP.md

services:
  gitlab-webhook:
    image: gitlab-webhook-receiver:latest
    container_name: gitlab-webhook
    restart: unless-stopped
    
    # Build configuration
    build:
      context: ../docker/gitlab-webhook
      dockerfile: Dockerfile
    
    # Security
    security_opt:
      - no-new-privileges:true
    
    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 64M
    
    # Network configuration
    networks:
      - traefik-network
      - monitoring-network
    ports:
      - "3002:3002"
    
    # Volume mounts
    volumes:
      # Event logs and audit trail
      - gitlab-webhook-logs:/app/logs:z
    
    # Environment variables
    environment:
      - TZ=America/New_York
      - GITLAB_WEBHOOK_PORT=3002
      - GITLAB_WEBHOOK_EMAIL=jbyrd@redhat.com
      - GITLAB_WEBHOOK_FROM=hatter@miraclemax
      - SMTP_SERVER=localhost
      - SMTP_PORT=25
      # Optional: Set webhook secret for security
      # - GITLAB_WEBHOOK_SECRET=${GITLAB_WEBHOOK_SECRET}
    
    # Health check
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3002/health || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 10s
    
    labels:
      # Service identification
      - "com.miraclemax.service=gitlab-webhook"
      - "com.miraclemax.version=1.0.0"
      - "com.miraclemax.description=GitLab webhook receiver for issue notifications"
      
      # Backup configuration
      - "com.miraclemax.backup=standard"
      - "com.miraclemax.backup.path=/app/logs"
      - "com.miraclemax.backup.frequency=weekly"
      
      # Monitoring
      - "com.miraclemax.monitor=true"
      - "com.miraclemax.health.port=3002"
      - "com.miraclemax.health.path=/health"
      
      # Traefik routing
      - "traefik.enable=true"
      - "traefik.http.routers.gitlab-webhook.rule=Host(`gitlab-webhook.jbyrd.org`)"
      - "traefik.http.routers.gitlab-webhook.entrypoints=web,websecure"
      - "traefik.http.services.gitlab-webhook.loadbalancer.server.port=3002"
      
      # Security: Internal only (GitLab CEE access)
      - "traefik.http.routers.gitlab-webhook.middlewares=security-headers@file,rate-limit@file"

# Named volumes
volumes:
  gitlab-webhook-logs:
    driver: local

# Networks
networks:
  traefik-network:
    external: true
  monitoring-network:
    external: true

