version: '3.8'

# n8n Workflow Automation
# Purpose: Workflow automation and integration platform
# Documentation: https://docs.n8n.io/

services:
  n8n:
    image: n8nio/n8n:1.60.1  # Pinned version
    container_name: n8n
    restart: unless-stopped
    
    # Security
    security_opt:
      - no-new-privileges:true
    
    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M
    
    # Network configuration
    networks:
      - traefik-network
      - monitoring-network
    ports:
      - "5678:5678"
    
    # Volume mounts
    volumes:
      # Data directory (workflows, credentials, etc.)
      - n8n-data:/home/node/.n8n:z
      
      # Optional: Local files for file operations
      - /home/jbyrd/n8n-files:/files:z
    
    # Environment variables
    environment:
      - TZ=America/New_York
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      # SECURITY: Set password via secrets
      # - N8N_BASIC_AUTH_PASSWORD=${N8N_PASSWORD}
      
      # Webhook URL (adjust if using Traefik)
      - WEBHOOK_URL=http://miraclemax.local:5678/
      
      # Execution mode - QUEUE for Redis-backed async execution
      - EXECUTIONS_MODE=queue
      - QUEUE_BULL_REDIS_HOST=redis
      - QUEUE_BULL_REDIS_PORT=6379
      - QUEUE_BULL_REDIS_DB=0
      - QUEUE_RECOVERY_INTERVAL=60  # Check for stalled jobs every 60s
      
      # Execution timeouts
      - EXECUTIONS_TIMEOUT=300
      - EXECUTIONS_TIMEOUT_MAX=600
      
      # Data retention
      - EXECUTIONS_DATA_SAVE_ON_ERROR=all
      - EXECUTIONS_DATA_SAVE_ON_SUCCESS=all
      - EXECUTIONS_DATA_MAX_AGE=168  # 7 days
      
      # Performance optimization
      - EXECUTIONS_DATA_PRUNE=true
      - EXECUTIONS_DATA_PRUNE_MAX_COUNT=10000
    
    # Health check
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:5678/healthz || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 45s
    
    labels:
      # Service identification
      - "com.miraclemax.service=n8n"
      - "com.miraclemax.version=1.60.1"
      - "com.miraclemax.description=Workflow automation platform"
      
      # Backup configuration (IMPORTANT - contains workflows and credentials)
      - "com.miraclemax.backup=important"
      - "com.miraclemax.backup.path=/home/node/.n8n"
      - "com.miraclemax.backup.frequency=daily"
      - "com.miraclemax.backup.encryption=required"  # Contains credentials
      
      # Monitoring
      - "com.miraclemax.monitor=true"
      - "com.miraclemax.health.port=5678"
      - "com.miraclemax.health.path=/healthz"
      
      # Traefik routing
      - "traefik.enable=true"
      - "traefik.http.routers.n8n.rule=Host(`n8n.miraclemax.local`)"
      - "traefik.http.services.n8n.loadbalancer.server.port=5678"
      
      # Security: Already has basic auth, but consider adding IP whitelist
      # - "traefik.http.routers.n8n.middlewares=internal-only@file"

# Named volumes
volumes:
  n8n-data:
    driver: local

# Networks
networks:
  traefik-network:
    external: true
  monitoring-network:
    external: true

