#!/bin/bash
# TAM Portfolio Setup Tool
# Helps TAMs create and maintain their account portfolio configuration

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

CONFIG_DIR="$HOME/.config/rfe-automation"
CONFIG_FILE="$CONFIG_DIR/tam-portfolio.yml"

echo -e "${PURPLE}🎯 TAM Portfolio Setup Tool${NC}"
echo -e "${PURPLE}===========================${NC}"
echo ""

# Create config directory if it doesn't exist
mkdir -p "$CONFIG_DIR"

# Check if config already exists
if [ -f "$CONFIG_FILE" ]; then
    echo -e "${YELLOW}⚠️  TAM portfolio config already exists at:${NC}"
    echo -e "${BLUE}$CONFIG_FILE${NC}"
    echo ""
    read -p "Do you want to update it? (y/N): " -n 1 -r
    echo ""
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo -e "${GREEN}✅ Keeping existing configuration.${NC}"
        exit 0
    fi
fi

echo -e "${BLUE}📋 Let's set up your TAM portfolio configuration...${NC}"
echo ""

# Get TAM information
read -p "Enter your name: " TAM_NAME
read -p "Enter your email: " TAM_EMAIL

echo ""
echo -e "${CYAN}🔍 Analyzing your case data to suggest accounts...${NC}"

# Get case data and suggest accounts
TEMP_FILE=$(mktemp)
rhcase list --all --format json 2>/dev/null | jq -r '
  group_by(.accountNumber) | 
  map({
    account_number: .[0].accountNumber,
    customer_name: .[0].account.name,
    account_name: .[0].accountName,
    total_cases: length,
    active_cases: map(select(.isClosed == false)) | length,
    sbr_groups: [.[].sbrGroup] | unique,
    vertical: .[0].account.vertical
  }) | 
  sort_by(-.active_cases) | 
  .[] | 
  select(.active_cases >= 1) |
  "\(.account_number)|\(.customer_name)|\(.account_name)|\(.active_cases)|\(.total_cases)|\(.sbr_groups | join(","))|\(.vertical // "Unknown")"
' > "$TEMP_FILE" || {
    echo -e "${RED}❌ Failed to analyze case data. Please check rhcase configuration.${NC}"
    exit 1
}

echo ""
echo -e "${GREEN}📊 Found the following accounts with case activity:${NC}"
echo ""

# Display suggested accounts
ACCOUNTS=()
while IFS='|' read -r account_number customer_name account_name active_cases total_cases sbr_groups vertical; do
    echo -e "${CYAN}Account: $account_number${NC}"
    echo -e "  Customer: $customer_name"
    echo -e "  Account Name: $account_name"
    echo -e "  Active Cases: $active_cases"
    echo -e "  Total Cases: $total_cases"
    echo -e "  SBR Groups: $sbr_groups"
    echo -e "  Vertical: $vertical"
    echo ""
    
    read -p "Include this account in your portfolio? (Y/n): " -n 1 -r
    echo ""
    if [[ ! $REPLY =~ ^[Nn]$ ]]; then
        # Get priority
        echo "Priority options: high, medium, low"
        read -p "Priority for $customer_name (default: medium): " priority
        priority=${priority:-medium}
        
        # Get products
        echo "Products (comma-separated, e.g., Ansible,OpenShift,RHEL):"
        read -p "Products for $customer_name (default: $sbr_groups): " products
        products=${products:-$sbr_groups}
        
        # Get description
        read -p "Description (optional): " description
        
        ACCOUNTS+=("$account_number|$customer_name|$account_name|$products|$vertical|$priority|$description")
    fi
done < "$TEMP_FILE"

rm "$TEMP_FILE"

# Generate config file
echo -e "${BLUE}📝 Generating TAM portfolio configuration...${NC}"

cat > "$CONFIG_FILE" << EOF
---
# TAM Portfolio Configuration
# Generated by TAM Portfolio Setup Tool
# Edit this file to maintain your account portfolio

tam_name: "$TAM_NAME"
tam_email: "$TAM_EMAIL"

# Portfolio Definition
accounts:
EOF

for account_info in "${ACCOUNTS[@]}"; do
    IFS='|' read -r account_number customer_name account_name products vertical priority description <<< "$account_info"
    
    cat >> "$CONFIG_FILE" << EOF
  - account_number: "$account_number"
    account_name: "$account_name"
    customer_name: "$customer_name"
    products: [$(echo "$products" | sed 's/,/", "/g' | sed 's/^/"/' | sed 's/$/"/')]
    vertical: "$vertical"
    priority: "$priority"
    description: "$description"
EOF
done

cat >> "$CONFIG_FILE" << EOF

# Validation Settings
validation_mode: "active_cases"  # Validate portfolio against active cases
auto_suggestions: true           # Suggest new accounts based on case activity
min_cases_for_suggestion: 3     # Minimum cases to suggest a new account

# Discovery Settings
include_closed: false
min_cases: 1
EOF

echo ""
echo -e "${GREEN}✅ TAM portfolio configuration created!${NC}"
echo -e "${BLUE}📁 Location: $CONFIG_FILE${NC}"
echo ""
echo -e "${CYAN}📋 Your portfolio includes ${#ACCOUNTS[@]} accounts:${NC}"
for account_info in "${ACCOUNTS[@]}"; do
    IFS='|' read -r account_number customer_name account_name products vertical priority description <<< "$account_info"
    echo -e "  • $customer_name ($account_number) - $products"
done

echo ""
echo -e "${PURPLE}🚀 Next Steps:${NC}"
echo -e "1. Review your configuration: ${BLUE}cat $CONFIG_FILE${NC}"
echo -e "2. Test your portfolio: ${BLUE}make discover-portfolio${NC}"
echo -e "3. Generate reports: ${BLUE}make generate-tam-reports${NC}"
echo -e "4. Edit your portfolio anytime: ${BLUE}$CONFIG_FILE${NC}"

echo ""
echo -e "${GREEN}🎯 TAM Portfolio Setup Complete!${NC}"
